# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_defaultevent_event_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultevent',
            name='event_class',
        ),
        migrations.AddField(
            model_name='event',
            name='event_class',
            field=models.CharField(default='non-active', max_length=15),
        ),
    ]
